from flask import Flask, render_template, redirect, url_for, request
import time
from threading import Timer

app = Flask(__name__, template_folder='templates', static_folder='static')

# Simple session storage (for hackathon purposes)
processing_active = False

@app.route('/')
def index():
    """Landing page with hero section"""
    return render_template('index.html')

@app.route('/upload')
def upload():
    """Upload page"""
    return render_template('upload.html')

@app.route('/process', methods=['POST'])
def process():
    """Process the uploaded file - simulates 2-3 second processing"""
    # Check if file was uploaded
    if 'file' not in request.files:
        return redirect(url_for('upload'))
    
    file = request.files['file']
    if file.filename == '':
        return redirect(url_for('upload'))
    
    # Simulate processing by redirecting to processing page
    return render_template('processing.html')

@app.route('/download')
def download():
    """Download page with success message"""
    return render_template('download.html')

@app.route('/api/download-file')
def api_download_file():
    """API endpoint to trigger file download (dummy implementation)"""
    # In a real app, this would generate and serve the formatted document
    # For hackathon, we'll just return a simple text file
    from flask import send_file
    from io import BytesIO
    
    # Create a dummy formatted document
    content = b"""ManuFormat - Sample Formatted Document
======================================

This is a sample formatted scholarly document.
Your research paper has been successfully formatted
to journal standards using ManuFormat.

[Your actual manuscript content would appear here,
formatted according to academic standards]

Generated by ManuFormat - Format research papers & manuscripts.
"""
    
    bytes_io = BytesIO(content)
    bytes_io.seek(0)
    
    return send_file(
        bytes_io,
        mimetype='text/plain',
        as_attachment=True,
        download_name='formatted_manuscript.txt'
    )

if __name__ == '__main__':
    # Run the Flask app in debug mode
    app.run(debug=True, port=5000, host='127.0.0.1')


